# Generated by Django 2.0 on 2019-12-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RateCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd', models.FloatField(default=1.0, verbose_name='Dollar')),
                ('uah', models.FloatField(max_length=1000, verbose_name='UAH')),
                ('timestamp', models.DateField()),
            ],
        ),
    ]
